#<% require 'kitchen-sync' %>
---
driver_config:
   digitalocean_access_token: <%= ENV['DIGITALOCEAN_API_TOKEN'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
- name: ubuntu-15.10
  driver_plugin: digitalocean
  driver_config:
    size: 2gb
    image: ubuntu-15-10-x64
    region: <%= ENV['DIGITALOCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEYS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>
  transport:
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

suites:
- name: default
  run_list:
  - recipe[chef-docker-images::service]
  - recipe[chef-docker-images::default]
