#<% require 'kitchen-sync' %>
---
driver_config:
   aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
   instance_type: <%= ENV['EC2_INSTANCE_TYPE'] %>
   availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
- name: ubuntu-15.10
  driver_plugin: ec2
  driver_config:
    # image_id: ami-3e52445f # us-west ubuntu-15.10
    image_id: ami-cfdea4a5 # us-east ubuntu-15.10
    security_group_ids: <%= ENV['EC2_SECURITY_GROUP_IDS'] %>
  transport:
    username: ubuntu
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt::default]

suites:
- name: default
  run_list:
  - recipe[chef-docker-images::service]
  - recipe[chef-docker-images::default]
